import React,{useEffect,useState} from 'react';
import {Alert,Text,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {File,Paths} from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import {api} from '../../src/services/api';
import {Button,Busy,Card,Field,Label,Screen,s,C} from '../../src/components/ui';

export default function Details(){const{id}=useLocalSearchParams<{id:string}>();const[file,setFile]=useState<any>();const[perms,setPerms]=useState<any[]>([]);const[email,setEmail]=useState('');const[level,setLevel]=useState<'download'|'view'>('download');const[busy,setBusy]=useState(false);const[progress,setProgress]=useState<number|null>(null);const[error,setError]=useState('');
 async function load(){try{const f=await api.file(String(id));setFile(f.data.file);if(f.data.file.access==='owner'){const p=await api.permissions(String(id));setPerms(p.data.permissions||[])}}catch(e:any){setError(e.message)}}useEffect(()=>{void load()},[id]);
 async function download(){setBusy(true);setProgress(0);try{const r=await api.download(String(id),setProgress);const safe=file.originalName.replace(/[\\/:*?"<>|]/g,'_');const local=new File(Paths.cache,safe);local.create({overwrite:true});local.write(new Uint8Array(r.data));if(await Sharing.isAvailableAsync())await Sharing.shareAsync(local.uri,{mimeType:file.mimeType,dialogTitle:'Save or open file'});else Alert.alert('Downloaded',`Saved to ${local.uri}`)}catch(e:any){Alert.alert('Download failed',e.message)}finally{setBusy(false);setProgress(null)}}
 async function share(){if(!/^\S+@\S+\.\S+$/.test(email)){Alert.alert('Invalid email','Enter the registered recipient email.');return}try{await api.share(String(id),email.trim(),level);setEmail('');Alert.alert('Shared',`${level==='download'?'Download':'View'} access granted.`);await load()}catch(e:any){Alert.alert('Share failed',e.message)}}
 function revoke(permissionId:string,recipient:string){Alert.alert('Revoke access',`Remove access for ${recipient}?`,[{text:'Cancel',style:'cancel'},{text:'Revoke',style:'destructive',onPress:async()=>{try{await api.revoke(permissionId);await load()}catch(e:any){Alert.alert('Revoke failed',e.message)}}}])}
 function remove(){Alert.alert('Delete file',`Permanently delete ${file.originalName}?`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api.removeFile(String(id));router.back()}catch(e:any){Alert.alert('Delete failed',e.message)}}}])}
 if(!file)return <Screen title="File details">{error?<Text style={{color:C.red}}>{error}</Text>:<Busy/>}</Screen>;
 return <Screen title="File details"><Card><Text style={{fontWeight:'800',fontSize:19,color:C.nav}}>{file.originalName}</Text><Text style={s.bodyText}>{file.mimeType} · {(file.size/1024).toFixed(1)} KB</Text><Text style={s.muted}>Uploaded {new Date(file.createdAt).toLocaleString()}</Text><Text style={s.muted}>Owner: {file.ownerName||file.ownerEmail||'Owner'}</Text><Text style={s.muted}>Access: {file.access} · Server encryption: AES-256-GCM</Text>{busy&&progress!==null&&<Text style={s.muted}>Downloading {progress}%</Text>}<Button title={busy?'Downloading…':'Download'} disabled={busy||file.access==='view'} onPress={()=>void download()}/></Card>{file.access==='owner'&&<><Card><Text style={{fontWeight:'700',color:C.nav}}>Share file</Text><Label>Registered user email</Label><Field value={email} onChangeText={setEmail} keyboardType="email-address"/><View style={{flexDirection:'row',gap:8}}><Button title={level==='download'?'✓ Download':'Download'} secondary onPress={()=>setLevel('download')}/><Button title={level==='view'?'✓ View':'View'} secondary onPress={()=>setLevel('view')}/></View><Button title={`Grant ${level} access`} onPress={()=>void share()}/></Card><Card><Text style={{fontWeight:'700',color:C.nav}}>People with access</Text>{perms.length?perms.map(p=><Text key={p.id||p._id} style={s.bodyText}>{p.userEmail} · {p.level}  <Text onPress={()=>revoke(p.id||p._id,p.userEmail)} style={{color:C.red}}>Revoke</Text></Text>):<Text style={s.muted}>No active shares.</Text>}<Button title="Delete file" secondary onPress={remove}/></Card></>}</Screen>
}
