import React from 'react';import {View,Text,Pressable,ActivityIndicator,StyleSheet,TextInput,ScrollView} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';
export const C={nav:'#102747',blue:'#2463eb',bg:'#f3f6fb',ink:'#172b4d',muted:'#63748b',line:'#dce4ef',green:'#16865b',red:'#c23d4b',white:'#fff'};
export function Button({title,onPress,secondary=false,disabled=false}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.btn,secondary&&s.secondary,disabled&&{opacity:.55}]}><Text style={[s.btnText,secondary&&{color:C.nav}]}>{title}</Text></Pressable>}
export function Screen({children,title,refresh}:{children:React.ReactNode;title:string;refresh?:()=>void}){return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><ScrollView style={s.screen} contentContainerStyle={s.body} keyboardShouldPersistTaps="handled"><Text style={s.title}>{title}</Text>{children}</ScrollView></SafeAreaView>}
export function Card({children,style}:{children:React.ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Field(props:any){return <TextInput placeholderTextColor="#8a99ad" {...props} style={[s.input,props.style]} autoCapitalize={props.autoCapitalize||'none'}/>}
export function Busy(){return <View style={{padding:28}}><ActivityIndicator size="large" color={C.blue}/></View>}
export function Label({children}:{children:React.ReactNode}){return <Text style={s.label}>{children}</Text>}
export const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg},body:{padding:20,paddingBottom:40,gap:14},title:{fontSize:27,fontWeight:'800',color:C.nav,marginBottom:4},card:{backgroundColor:C.white,borderRadius:18,padding:17,gap:9,borderWidth:1,borderColor:'#e8edf4'},btn:{backgroundColor:C.blue,padding:14,borderRadius:12,alignItems:'center',marginVertical:3},secondary:{backgroundColor:'#eaf0fb'},btnText:{color:C.white,fontWeight:'700',fontSize:15},input:{backgroundColor:C.white,borderColor:C.line,borderWidth:1,borderRadius:11,padding:13,fontSize:16,color:C.ink},label:{color:C.muted,fontSize:13,fontWeight:'600'},bodyText:{fontSize:15,color:C.ink},muted:{fontSize:13,color:C.muted}});
